package andorid.example.jetpack_compose_assignment_1

val sampleCourses = listOf(
    CourseModel( "Fundamentals of Cybersecurity","SECT-3460", 4,"This course course offers an essential introduction to the principles, practices, and technologies used to protect information systems from cyber threats. Students will learn about cybersecurity concepts, including threat analysis, risk management, cryptography, network security, access control, and incident response. The course combines theoretical knowledge with practical exercises, providing students with hands-on experience in identifying and mitigating security vulnerabilities. By the end of the course, students will be equipped with the foundational skills necessary for pursuing advanced studies or careers in cybersecurity."),
    CourseModel("Database Systems", "SECT2201", 4, "This course course provides a solid foundation in the design, implementation, and management of database systems. Students will explore core database concepts, including data modeling, relational database design, Structured Query Language (SQL), normalization, indexing, and transaction management. The course also covers advanced topics such as NoSQL databases, database security, and performance optimization. Through hands-on projects, students will gain practical experience in designing and managing database solutions, preparing them for real-world database administration and development roles."),
    CourseModel("Mobile Application Development", "SECT-3151", 3,  "This course provides a comprehensive introduction to designing, developing, and deploying mobile applications for various platforms, including Android and iOS. Students will learn the fundamentals of mobile app development, including user interface design, data management, API integration, and mobile security. The course emphasizes practical, hands-on experience, enabling students to build fully functional mobile applications using industry-standard tools and frameworks. By the end of the course, students will have the skills to create, test, and publish mobile apps, preparing them for careers in mobile application development."),
    CourseModel("Object Oriented Programming", "SECT-3301", 3, "This course course introduces students to the principles and techniques of object-oriented programming (OOP), focusing on the design and implementation of software using objects, classes, inheritance, polymorphism, encapsulation, and abstraction. Students will learn how to structure code for scalability and maintainability while solving real-world problems using an OOP language such as Java, Python, or C++. Through hands-on exercises and projects, they will gain practical experience in building modular, reusable, and efficient software applications."),
    CourseModel("Fundamentals of AI","SECT-3370",4,"This course course provides an introduction to the core concepts, techniques, and applications of Artificial Intelligence (AI). Students will explore key topics, including machine learning, natural language processing, computer vision, robotics, and ethical considerations in AI. The course emphasizes hands-on experience with AI tools and frameworks, enabling students to build simple AI models and understand their real-world applications. By the end of the course, students will have a solid foundation in AI principles, preparing them for advanced studies or careers in the field.")
)


